name: Bug report
description: File a bug report.
title: '[Bug]: '
labels: ['bug', 'community']
projects: ['xames3/1']
assignees:
  - 'xames3'
  - 'jfmartinez4'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! Your feedback is essential to help us improve. Please follow the template and provide as much detail as possible.

        We truly appreciate you bringing this to our attention. Providing clear and concise details helps us address issues faster. Before you proceed, please ensure you've checked the following:
        - [ ] You've searched [open issues](https://github.com/ciesin-geospatial/TOPSTSCHOOL-SPHINX/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) to see if your bug has already been reported.
        - [ ] You've searched [closed issues](https://github.com/ciesin-geospatial/TOPSTSCHOOL-SPHINX/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) to see if your bug has already been fixed.
  - type: input
    id: bug-summary
    attributes:
      label: Brief summary
      description: Please provide a quick, one-sentence description of the bug.
      placeholder: 'e.g., I am unable to click on the Accounts Setup page.'
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: Describe your issue
      description: Describe the bug in detail. Include any steps necessary to reproduce it, what you expected to happen, and what actually happened.
      placeholder: While going through the website, I saw...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the behavior.
      placeholder: |
        1. Navigate to ...
        2. Scroll down to ....
        3. And click on ....
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen?
      placeholder: |
        I expected ..., but I'm seeing ...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: |
        Which Operating System you were using when the issue occurred?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - I use a different browser
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor...
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide any additional context or information you think would be helpful.
      placeholder: 'e.g., Error logs, related issues, or any recent changes in the environment'
  - type: checkboxes
    id: impact-level
    attributes:
      label: Bug severity
      description: How does this bug affect your work?
      options:
        - label: Minor
          required: false
        - label: Major
          required: false
        - label: Critical
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](#). 
      options:
        - label: I agree to follow TOPSTSCHOOL Sphinx's Code of Conduct.
          required: true
  - type: markdown
    attributes:
      value: |
        ## Next Steps
        Thank you for filling out the report! Once submitted, our team will review your issue and follow up as needed. Your contribution helps us immensely.

        If you have any questions or need to follow up, feel free to comment below your submission.
