# TOPSTSCHOOL Sphinx (Documentation) Building Pages Workflow
# ==========================================================
#
# Author: Akshay Mestry <xa@mes3.dev>
# Created on: Sunday, October 27 2024
# Last updated on: Sunday, October 27 2024

name: website-deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - $default-branch

permissions:
  contents: write

env:
  PUBLISH_BRANCH: docs

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: docs/build/canary
      SOURCE_DIR: docs/source
      PY_BUILD: 3.12.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_BUILD }}
          cache: pip
      - name: Build
        run: |
          echo "Clean installing latest version of sphinx and other runtime dependencies..."
          python -m pip install -Uq pip -rrequirements.txt
          echo "Building documentation pages..."
          sphinx-build -EWqa --builder html ${{ env.SOURCE_DIR }} ${{ env.OUTPUT_DIR }}
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: docs/build/canary
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          publish_dir: ${{ env.OUTPUT_DIR }}
          force_orphan: false
          enable_jekyll: false
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "topstschool[bot]"
          full_commit_message: ${{ github.event.head_commit.message }}
